# Generated by Django 5.2.4 on 2025-09-14 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('base_model', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='lora/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_lora_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('base_model', models.CharField(max_length=128)),
                ('steps', models.PositiveIntegerField(default=800)),
                ('rank', models.PositiveIntegerField(default=16)),
                ('lr', models.FloatField(default=0.0001)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('dataset_dir', models.CharField(max_length=512)),
                ('out_dir', models.CharField(max_length=512)),
                ('lora_file', models.FileField(blank=True, null=True, upload_to='lora/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
