# Generated by Django 5.2.4 on 2025-09-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_model', models.CharField(default='SG161222/Realistic_Vision_V4.0_noVAE', max_length=150)),
                ('file', models.FileField(upload_to='lora/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('num_inference_steps', models.PositiveIntegerField(default=80)),
                ('guidance_scale', models.FloatField(default=9.0)),
                ('extra_condition_scale', models.FloatField(default=1.2)),
                ('seed', models.BigIntegerField(default=1234)),
                ('canny_image', models.ImageField(upload_to='canny/')),
                ('output_image', models.ImageField(blank=True, upload_to='generated/')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('error', 'error')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator_app.loramodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dataset_path', models.CharField(max_length=500)),
                ('params_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('error', 'error')], default='queued', max_length=10)),
                ('logs_path', models.CharField(blank=True, max_length=500)),
                ('output_lora_file', models.FileField(blank=True, upload_to='lora/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
